name: exchangerate
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  intl: ^0.19.0 # <--- AGREGAR ESTO
  provider: ^6.1.2                      # AGREGAR
  shared_preferences: ^2.2.3            # AGREGAR
  sqflite: ^2.3.0          # AGREGAR
  path: ^1.8.3             # AGREGAR
  path_provider: ^2.1.1    # AGREGAR
  fl_chart: ^0.68.0 
  #flutter_local_notifications: ^17.2.3  # AGREGAR
  #workmanager: ^0.5.2 
  #home_widget: ^0.6.0  # AGREGAR para widget en pantalla de inicio
  #workmanager: ^0.5.2  # AGREGAR para actualizar en segundo plano
  local_auth: ^2.2.0  # AGREGAR para huella/PIN

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # Agrega esta línea

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/sflogo.png"
  
  # Android adaptive icon (Android 8+)
  adaptive_icon_background: "#FFFFFF"          # Fondo blanco
  adaptive_icon_foreground: "assets/icons/sflogo.png"  # Tu logo
  adaptive_icon_foreground_inset: 25           # Margen del logo (% del espacio)
  
                       # Elimina fondo transparente
  
  # Web
  web:
    generate: true
    image_path: "assets/icons/sflogo.png"
    background_color: "#FFFFFF"
    theme_color: "#009688"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/icons/sflogo.png"
    icon_size: 48
  
  # macOS
  macos:
    generate: true
    image_path: "assets/icons/sflogo.png"
